"""
Reads Unlimited Experience Network CSV and generates SQL inserts for:
  - book_partner  (one row per unique partner)
  - book_branch   (one row per location, linked to partner)

Output: scripts/insert_partners.sql
"""

import csv
import io

CSV_FILE = "scripts/Unlimited - Experience Network  2026.csv"
OUTPUT_FILE = "scripts/insert_partners.sql"

BOOK_CATEGORY_ID = 3
IS_ACTIVE = 1


def clean(value: str) -> str:
    """Escape single quotes for SQL."""
    if value is None:
        return ""
    return value.strip().replace("'", "''")


def main():
    # --- Read CSV ---
    with open(CSV_FILE, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    # --- Deduplicate partners (keep first occurrence of writeup/offer) ---
    partners: dict[str, dict] = {}   # partner_name -> {writeup, offer}
    branches: list[dict] = []        # all branch rows in order

    for row in rows:
        name = row["Name of Partner"].strip()
        if not name:
            continue

        if name not in partners:
            partners[name] = {
                "writeup": row.get("Writeup", "").strip(),
                "offer":   row.get("Offer", "").strip(),
            }

        branches.append({
            "partner_name": name,
            "address":      row.get("Street Address", "").strip(),
            "branch_name":  row.get("Region", "").strip(),
            "province":     row.get("Province", "").strip(),
        })

    # --- Build SQL ---
    lines = []
    lines.append("-- Generated by generate_partner_sql.py")
    lines.append("-- Partners: {}  |  Branches: {}".format(len(partners), len(branches)))
    lines.append("")
    lines.append("BEGIN TRANSACTION;")
    lines.append("")

    # One block per partner
    for name, info in partners.items():
        var = f"@pid_{_var_name(name)}"
        lines.append(f"-- *** {name} ***")
        lines.append(f"DECLARE {var} INT;")
        lines.append(
            f"INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)"
        )
        lines.append(
            f"VALUES (N'{clean(name)}', N'{clean(info['writeup'])}', N'{clean(info['offer'])}', "
            f"{BOOK_CATEGORY_ID}, {IS_ACTIVE});"
        )
        lines.append(f"SET {var} = SCOPE_IDENTITY();")
        lines.append("")

        # All branches for this partner
        partner_branches = [b for b in branches if b["partner_name"] == name]
        for b in partner_branches:
            lines.append(
                f"INSERT INTO book_branch (partner_id, address, branch_name, province)"
            )
            lines.append(
                f"VALUES ({var}, N'{clean(b['address'])}', N'{clean(b['branch_name'])}', N'{clean(b['province'])}');"
            )
        lines.append("")

    lines.append("COMMIT;")

    sql = "\n".join(lines)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(sql)

    print(f"Done. {len(partners)} partners, {len(branches)} branches -> {OUTPUT_FILE}")


# Build a safe T-SQL variable suffix from a partner name
def _var_name(name: str) -> str:
    safe = "".join(c if c.isalnum() else "_" for c in name)
    return safe[:50]


if __name__ == "__main__":
    main()
