-- Generated by generate_partner_sql.py
-- Partners: 46  |  Branches: 94

BEGIN TRANSACTION;

-- *** Acrobranch ***
DECLARE @pid_Acrobranch INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Acrobranch', N'Get your adrenaline pumping with our Tree-Top Adventures & Zip lines. Slide, balance, jump, crawl, dash, swing or stroll  expect the unexpected from this wild experience that brings you a variety of twists, turns, dips and thrills.', N'Buy 1 High Flying course & get another 1 High Flying one free.', 3, 1);
SET @pid_Acrobranch = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Acrobranch, N'Corner of Valley Rd &, Johannesburg Rd, Modderfontein, Lethabong', N'Johannesburg', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Acrobranch, N'The Big Red Barn, C/O Nelson & Glen Road, Sunlawns Estate, Olifantsfontein, Pretoria', N'Centurion', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Acrobranch, N'18 Honingnestkrans Street, Soutpan Road, Pretoria North', N'Pretoria North', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Acrobranch, N'Plot 328 Rocky Ridge Rd, Muldersdrift', N'Muldersdrift', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Acrobranch, N'Plot 55, Garsfontein Rd, Pretoria East, Tierpoort', N'Pretoria East', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Acrobranch, N'James & Ethel Gray Park, Melrose Street Extension, Johannesburg', N'Johannesburg', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Acrobranch, N'64a Springside Rd, Everton, Hillcrest', N'Hillcrest', N'KwaZulu Natal');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Acrobranch, N'2 Zwartkop Rd, Prestbury, Pietermaritzburg', N'Pietermaritzburg', N'KwaZulu Natal');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Acrobranch, N'1 Hout Bay Main Road, Constantia Nek', N'Cape Town', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Acrobranch, N'Timberlake Organic Village, N2 between Wilderness and Sedgefield, George', N'George', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Acrobranch, N'Klein Joostenberg Farm, Muldersvlei Rd, Stellenbosch', N'Stellenbosch', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Acrobranch, N'The Farmyard on Rainhill Farm, 36 Donkerhoek Rd, Donkerhoek, Rustenburg', N'Rustenburg', N'North West');

-- *** Adventure Golf ***
DECLARE @pid_Adventure_Golf INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Adventure Golf', N'Adventure Golf exists to provide that integral space where ALL people can take a break from trepidation. We have spent the last three decades providing our patrons with memories, entertainment, and smiles and there is NOTHING that we value more than that special bond between family.', N'Buy 1 ticket and get 1 free ticket', 3, 1);
SET @pid_Adventure_Golf = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Adventure_Golf, N'Ferndale on Republic, Republic Rd, Ferndale, Randburg', N'Randburg', N'Gauteng');

-- *** All Out Adventures ***
DECLARE @pid_All_Out_Adventures INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'All Out Adventures', N'All Out Adventures , situated in the unspoilt KZN Northern Drakensberg just off the R74, mid way between Joburg and Durban, offers 10 awesome activities at one spectacular venue. Highlights include SAs fastest Cable Tour, Adventure Quad Trails, 150kms of marked mountain bike trails, and a hair raising 17 meter free fall King Swing accessed by a wooden spiral stair case that snakes 21 meters to the tree tops.', N'Pay for 1 king swing ticket and get 1 free ticket', 3, 1);
SET @pid_All_Out_Adventures = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_All_Out_Adventures, N'Moeggestap Farm Off D119, Bergville', N'Bergville', N'KwaZulu Natal');

-- *** Animal Farm Yard ***
DECLARE @pid_Animal_Farm_Yard INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Animal Farm Yard', N'A delightful venue with a wide selection of animals, big and small. Owner managed by a couple, who clearly love animals. The tea garden offers light lunches, breakfast, cakes and beverages in a lovely setting overlooking the farms on the opposite side of the valley.', N'Buy 1 entry ticket and get 1 free.', 3, 1);
SET @pid_Animal_Farm_Yard = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Animal_Farm_Yard, N'3 Lello Rd, Assagay, Hillcrest', N'Hillcrest', N'KwaZulu Natal');

-- *** Apex Indoor Trampoline ***
DECLARE @pid_Apex_Indoor_Trampoline INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Apex Indoor Trampoline', N'APEX is locally owned, operated and dedicated to the Rustenburg community and to our guests. We are enthusiastic about special needs, obesity, health and fitness.', N'Pay for 1 Jumper session and get a 30 minute session free.', 3, 1);
SET @pid_Apex_Indoor_Trampoline = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Apex_Indoor_Trampoline, N'200 Bethlehem St, Rustenburg North, Rustenburg', N'Rustenburg', N'North West');

-- *** Be Up Park ***
DECLARE @pid_Be_Up_Park INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Be Up Park', N'We have a wide variety of activities to guarantee a Fun time while exercising. Our activities include a Trampoline Zone, an AltiGame, Climbing Walls and a huge Kids Maze! Put all this together and you can see why be.UP Park is a favourite destination for the most memorable birthday parties, milestone events, group events, corporate outings, charitable functions and more.', N'Buy 1 climbing session and get 1 free', 3, 1);
SET @pid_Be_Up_Park = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Be_Up_Park, N'Gardener Place, Rose Innes Street, Pinelands, Western Cape', N'Pinelands', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Be_Up_Park, N'17 Dock Street, Victoria & Alfred Waterfront, Cape Town', N'Cape Town', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Be_Up_Park, N'Gateway Theatre of Shopping, 2nd Floor  Shop E-064, Umhlanga Ridge', N'Umhlanga Ridge', N'KwaZulu Natal');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Be_Up_Park, N'Cresta Shopping Centre, Cnr Beyers Naude Drive &, Weltevreden Rd, Cresta, Randburg', N'Randburg', N'Gauteng');

-- *** Blades & Triggers Paintball Field ***
DECLARE @pid_Blades___Triggers_Paintball_Field INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Blades & Triggers Paintball Field', N'A day out at Blades & Triggers  Paintball Field is sure to be an action packed adventure. Conveniently located on the corner of North Rand Road and Rietfontein Road in Boksburg within walking distance of East Rand Mall. Most importantly, youre in safe hands at our field. Our staff is well trained and experienced in delivering high quality paintball action.', N'Buy 1 get 1 free applicable to the Standard Package per person (The standard package includes the following 1 x rental gun, 1 x rental mask, 1 x overall, 100 x paintballs)', 3, 1);
SET @pid_Blades___Triggers_Paintball_Field = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Blades___Triggers_Paintball_Field, N'157 N Rand Rd, Beyers Park, Boksburg', N'Boksburg', N'Gauteng');

-- *** Blasters Family Entertainment Centre ***
DECLARE @pid_Blasters_Family_Entertainment_Centre INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Blasters Family Entertainment Centre', N'Blasters Mossel Bay family entertainment centre is a place where the whole family can come to have some fun together. Our giant indoor jungle gym is the largest in the Garden Route, and there is plenty of space for the kids aged 0-12 to run around and play. The games arcade, blacklight putt-putt, and pool tables are there for older kids and adults to enjoy. We also have a snooker table for our dads.', N'Buy 1 entry ticket and get 1 free.', 3, 1);
SET @pid_Blasters_Family_Entertainment_Centre = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Blasters_Family_Entertainment_Centre, N'23 Mascador St, Voorbaai, Mossel Bay', N'Mossel Bay', N'Western Cape');

-- *** Bounce ***
DECLARE @pid_Bounce INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Bounce', N'A spring-loaded urban playground for free-jumping where hard surfaces are replaced with circus-grade.', N'Pay for 1 miniBOUNCER Jumper session 1 hour and get a 1 hour session free', 3, 1);
SET @pid_Bounce = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Bounce, N'Shop U39 Cornubia Mall, Flanders Dve Mt. Edgecombe', N'Umhlanga', N'KwaZulu Natal');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Bounce, N'Amarand Ave, Level 2, Central Square, Waterkloof Ext 2 Centurion', N'Menlyn', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Bounce, N'Menlyn Maine, Amarand Ave, Central Square, Waterkloof Glen, Pretoria', N'Pretoria', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Bounce, N'L006, Cornubia Mall, Tecoma Road, Blackburn Estate, Durban', N'Durban', N'KwaZulu Natal');

-- *** Bushwhacked Outdoor Adventures ***
DECLARE @pid_Bushwhacked_Outdoor_Adventures INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Bushwhacked Outdoor Adventures', N'River Rafting specialists, based at our Orange River campsite, Fiddlers Creek, Bushwhacked promises you adventure, fun, relaxation, thrills, awesome scenery, great vibe, fantastic people, brilliant food, mind-blowing sunsets, tranquil sunrises, birdlife, peace and an experience of a life time.', N'Pay for 1 adult night camping experience and get 1 free', 3, 1);
SET @pid_Bushwhacked_Outdoor_Adventures = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Bushwhacked_Outdoor_Adventures, N'Plot 26 Fiddlers Creek, Kotzeshoop', N'Kotzeshoop', N'Northern Cape');

-- *** Butterfly Valley ***
DECLARE @pid_Butterfly_Valley INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Butterfly Valley', N'At Ramsgate Butterfly Valley, we specialize in South African butterflies. Unlike most other butterfly farms which import pupae, we breed most of our own butterflies and are therefore able to present the entire life-cycle of these amazing creatures to the public.', N'Buy 1 entry ticket and get 1 free.', 3, 1);
SET @pid_Butterfly_Valley = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Butterfly_Valley, N'Fascadale Rd, Ramsgate Beach, Ramsgate', N'Ramsgate', N'KwaZulu Natal');

-- *** Castle of Good Hope ***
DECLARE @pid_Castle_of_Good_Hope INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Castle of Good Hope', N'The Castle of Good Hope known locally as the Castle or Cape Town Castle is a bastion fort built in the 17th century in Cape Town, South Africa. Originally located on the coastline of Table Bay, following land reclamation the fort is now located inland.', N'Buy 1 get 1 free applicable to the entrance fee', 3, 1);
SET @pid_Castle_of_Good_Hope = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Castle_of_Good_Hope, N'Darling St & Buitenkant St, Cape Town', N'Cape Town', N'Western Cape');

-- *** Ceres Zipline Adventures ***
DECLARE @pid_Ceres_Zipline_Adventures INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Ceres Zipline Adventures', N'Come and experience this 1,4km of pure adrenaline Eco Adventure, consisting of 8 slides varying from 100-290m in length. This Eco-Adventure is safe, fast and long. The tour takes place in the Schurweberg Mountains below the Koekedouw Dam in Ceres.', N'Buy 1 Go-Pro Rental and get 1 free.', 3, 1);
SET @pid_Ceres_Zipline_Adventures = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Ceres_Zipline_Adventures, N'1 Voortrekker St, Ceres', N'Ceres', N'Western Cape');

-- *** Cheetah Experience ***
DECLARE @pid_Cheetah_Experience INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Cheetah Experience', N'Cheetah Experience is a non-profit endangered species breeding centre. We are home to a number of endangered and threatened species, including cheetahs, leopards, male non-breeding lions, servals, caracals, African wildcats, wolves, meerkats and a Siberian tiger. Our project takes in rescued animals from the local area, so we also have various animals from time to time, including a goat and antelope.', N'Buy 1 tour ticket and get 1 free', 3, 1);
SET @pid_Cheetah_Experience = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Cheetah_Experience, N'Farm 20, R101, Bela-Bela', N'Bela bela', N'Limpopo');

-- *** CK Paintball ***
DECLARE @pid_CK_Paintball INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'CK Paintball', N'Our batter field offers a absolutely fantastic terrain with stream running through the field. Trees provide shade during hot days & shelter when it rains. Tick and thorn free.', N'Buy 1 get 1 free applicable to the person who books the game.', 3, 1);
SET @pid_CK_Paintball = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_CK_Paintball, N'Helderberg Farm, Klein Helderbergpad, Somerset West, South Africa', N'Somerset West', N'Western Cape');

-- *** Clarens Extreme Adventures ***
DECLARE @pid_Clarens_Extreme_Adventures INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Clarens Extreme Adventures', N'Clarens Xtreme are the Great Adventure People. We are a team of energetic adventurers seeking to experience the real world with a grassroots approach to adventure and team building.', N'Buy 1 ticket and get 1 free ticket', 3, 1);
SET @pid_Clarens_Extreme_Adventures = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Clarens_Extreme_Adventures, N'531 Sias Oosthuizen St, Clarens', N'Clarens', N'Western Cape');

-- *** Clubventure  Zipline Tours ***
DECLARE @pid_Clubventure__Zipline_Tours INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Clubventure  Zipline Tours', N'Clubventure offers an awesome zipline tour with a difference. You can enjoy life from a birds eye view while sliding on Zipline cables on a 1,5km Zipline Tour. After a leisurely nature walk to the top of the cliff you are introduced to the 1st in the world all new Para zip', N'Buy 1 Zipline Tour and get 1 Zipline Tour free', 3, 1);
SET @pid_Clubventure__Zipline_Tours = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Clubventure__Zipline_Tours, N'Area, Clubventure 1369 Hopewell Farm, Esenembe Road', N'Ballito', N'KwaZulu Natal');

-- *** Creative Dance Academy ***
DECLARE @pid_Creative_Dance_Academy INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Creative Dance Academy', N'Creative Dance Academy is a dance academy specializing in Ballet, Modern/Jazz, Contemporary and Dance Studies', N'Pay for 1 session and get and 1 session free.', 3, 1);
SET @pid_Creative_Dance_Academy = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Creative_Dance_Academy, N'Gardenia Park, Bloemfontein', N'Bloemfontein', N'Free State');

-- *** Dance Fever Studio ***
DECLARE @pid_Dance_Fever_Studio INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Dance Fever Studio', N'', N'Pay for 1 session and get 1 session free', 3, 1);
SET @pid_Dance_Fever_Studio = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Dance_Fever_Studio, N'Online', N'Online', N'Online');

-- *** DNA Paintball ***
DECLARE @pid_DNA_Paintball INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'DNA Paintball', N'Paintball is not just what we do, it is who we are, it is our passion, and this is why DNA Paintball South Africa will always be innovative in your paintball experiences.', N'Buy 1 standard entry ticket get 1 free', 3, 1);
SET @pid_DNA_Paintball = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_DNA_Paintball, N'cnr Robert Broom Street & Lud Hersch Rd, Krugersdorp', N'Krugersdorp', N'Gauteng');

-- *** Earth Adventures ***
DECLARE @pid_Earth_Adventures INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Earth Adventures', N'Earth Adventures is a young, dynamic and family driven adventure company. Three brothers with a passion for adventure set out to create a truly unique African experience.', N'Pay for 100 paintball bullets and get 100 free', 3, 1);
SET @pid_Earth_Adventures = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Earth_Adventures, N'Farm 21, Kopjeskraal, Parys', N'Parys', N'Free State');

-- *** Featherfoot Horses ***
DECLARE @pid_Featherfoot_Horses INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Featherfoot Horses', N'Featherfoot Horse Ranch is conveniently situated in Jeffreys Bay, on the Kabeljouws suburb on the edge of town, in the Eastern Cape of South Africa.', N'Buy 1 ticket and get 1 free ticket', 3, 1);
SET @pid_Featherfoot_Horses = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Featherfoot_Horses, N'5 Elm St, Kabeljous, Jeffreys Bay', N'Jeffreys Bay', N'Eastern Cape');

-- *** Go Bananaz ***
DECLARE @pid_Go_Bananaz INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Go Bananaz', N'A place where the kids can play mini sports on a play court, learn balance and coordination in a uniquely designed air gym and also literally Go Bananaz in a safe and controlled environment.', N'Buy 1 entry ticket and get 1 entry ticket free', 3, 1);
SET @pid_Go_Bananaz = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Go_Bananaz, N'20 Rockview Rd, Amanzimtoti', N'Amanzimtoti', N'KwaZulu Natal');

-- *** Gravity Trampoline Park ***
DECLARE @pid_Gravity_Trampoline_Park INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Gravity Trampoline Park', N'At Gravity Indoor Trampoline Park we are a very popular choice when it comes to fun-filled, memorable birthday parties. All our experienced staff are fully trained to ensure the safety off all our clients and are available in a heartbeat to assist you.', N'Buy 1 entry ticket and get 1 free ticket', 3, 1);
SET @pid_Gravity_Trampoline_Park = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Gravity_Trampoline_Park, N'Hemingways Mall, Two Rivers Dr, Cambridge Village, East London', N'East London', N'Eastern Cape');

-- *** Hakuna Matata Charters ***
DECLARE @pid_Hakuna_Matata_Charters INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Hakuna Matata Charters', N'Hakuna Matata Charters is bases in Durban, South Africa and is proud to be the leading charter boat company. We boast two of the most luxurious 58 foot catamarans', N'Buy 1sea cruise ticket and get 1 free ticket', 3, 1);
SET @pid_Hakuna_Matata_Charters = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Hakuna_Matata_Charters, N'2 Maritime Pl, Durban Central, Durban', N'Durban', N'KwaZulu Natal');

-- *** Heavenly Stables ***
DECLARE @pid_Heavenly_Stables INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Heavenly Stables', N'Revitalize yourself with an unforgettable riding experience along the charming seaside suburb of Sardinia Bay, Lovemore Park in Port Elizabeth and the exquisite freedom of cantering along the Indian Coast.', N'Pay for 1 riding lesson and get 1 free', 3, 1);
SET @pid_Heavenly_Stables = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Heavenly_Stables, N'953 Olive Ln, Lovemore Park, Gqeberha', N'Gqeberha', N'Eastern Cape');

-- *** Hunyani Snake City ***
DECLARE @pid_Hunyani_Snake_City INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Hunyani Snake City', N'Hunyani Snake City, short for Hunyani Reptile Educational Breeding Centre, invites you to view presentations and learn about the conservation of South African reptiles. Included in the deadly-dozen are eyeball cobras, mambas, king snakes, anacondas, rattle snakes, pythons and crocodiles.', N'Buy 1 entrance ticket and get 1 free.', 3, 1);
SET @pid_Hunyani_Snake_City = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Hunyani_Snake_City, N'17 Voortrekker Ave, Edenvale, Johannesburg', N'Johannesburg', N'Gauteng');

-- *** iJump ***
DECLARE @pid_iJump INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'iJump', N'With over 1000 square meters of wall-to-wall trampolines, our facility has a general jump arena, trampoline dodgeball, foam pits, slam dunk tracks, extreme jumping, fitness classes and more; including the exciting iKIDZ arena that houses over 400 square meters of trampoline and playground area reserved exclusively for the little ones.', N'Pay for 1 iJump and get and extra 1 hour free', 3, 1);
SET @pid_iJump = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_iJump, N'Corner Hendrik Potgieter and Christiaan de Wet, Strubens Valley, Roodepoort', N'Roodepoort', N'Gauteng');

-- *** Imhoff Snake And Reptile Rehabilitation Centre ***
DECLARE @pid_Imhoff_Snake_And_Reptile_Rehabilitation_Centre INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Imhoff Snake And Reptile Rehabilitation Centre', N'Imhoffs Snake Park is a reptile sanctuary and rehabilitation centre. Its also an excellent destination for anyone interested in observing and learning about some of the most fascinating reptile species.', N'Buy 1 ticket and get 1 free ticket', 3, 1);
SET @pid_Imhoff_Snake_And_Reptile_Rehabilitation_Centre = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Imhoff_Snake_And_Reptile_Rehabilitation_Centre, N'36 Old Mill Road, Ndabeni, Maitland, 7405', N'Maitland', N'Western Cape');

-- *** Johannesburg Zoo ***
DECLARE @pid_Johannesburg_Zoo INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Johannesburg Zoo', N'The Joburg Zoo is one of the most popular local and tourist attractions situated in the leafy northern suburb of Johannesburg. The Zoo covers 55 hectares of land and was founded in 1904, when land was donated to the public for recreational use by the firm of the late Hermann Ekstein.', N'Pay for 1 kid entrance fee and get 1 free', 3, 1);
SET @pid_Johannesburg_Zoo = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Johannesburg_Zoo, N'Shop U 30 Keyes, Jellicoe Ave, Rosebank, Johannesburg', N'Johannesburg', N'Gauteng');

-- *** Jump Street ***
DECLARE @pid_Jump_Street INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Jump Street', N'Jump Street can be enjoyed by just about anyone, of any age, shape and physical ability. But for those not feeling adventurous, why not relax at the Jump Café where we offer coffees and snacks whilst enjoying the fun from afar', N'Pay for 1 session open jump 1 hour and get 1 session free', 3, 1);
SET @pid_Jump_Street = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Jump_Street, N'9 Enterprise Way, Rivergate Business Park', N'Cape Town', N'Western Cape');

-- *** Jumpers lane ***
DECLARE @pid_Jumpers_lane INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Jumpers lane', N'At Jumpers Lane, we are more than just an indoor trampoline and leisure park - we are the pioneers of boundless fun and adventure in Bloemfontein. Our journey began with a vision to create a space where people of all ages could break free from the shackles of gravity.', N'Pay for 1 trampoline jump and get 1 hour free.', 3, 1);
SET @pid_Jumpers_lane = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Jumpers_lane, N'3 Lebomboberg Ave, Bainsvlei, Bloemfontein', N'Bloemfontein', N'Free State');

-- *** Jungle Tots ***
DECLARE @pid_Jungle_Tots INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Jungle Tots', N'Learning through play is the key to what we do at Jungletots.The groups of children are kept small so that there is an opportunity to spend quality time with each child and to expose them to many varied fun-filled experiences through drama, puppetry and imaginary games.', N'Book for 1 tiny tot session and get 1 free.', 3, 1);
SET @pid_Jungle_Tots = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Jungle_Tots, N'Dainfern, Gauteng', N'Dainfern', N'Gauteng');

-- *** Kololo Game Reserve ***
DECLARE @pid_Kololo_Game_Reserve INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Kololo Game Reserve', N'Kololo Game Reserve is situated in Limpopo, the northernmost province of South Africa, in the heart of the protected Waterberg nature area, close to the village of Vaalwater.', N'Pay for 1 Kololo Kids Safari and get 1 free.', 3, 1);
SET @pid_Kololo_Game_Reserve = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Kololo_Game_Reserve, N'Bakkerspas Road, Vaalwater', N'Vaalwater', N'Limpopo');

-- *** Moholoholo Animal Rehabilitation Centre ***
DECLARE @pid_Moholoholo_Animal_Rehabilitation_Centre INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Moholoholo Animal Rehabilitation Centre', N'Situated at the base of the majestic North Eastern Lowveld Drakensberg mountain range in the Limpopo Province of South Africa, Moholoholo offers a unique experience to all nature enthusiasts.', N'Pay for 1 Wildlife Rehabilitation Centre entrance fee and get entrance fee free.', 3, 1);
SET @pid_Moholoholo_Animal_Rehabilitation_Centre = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Moholoholo_Animal_Rehabilitation_Centre, N'Hoedspruit', N'Hoedspruit', N'Limpopo');

-- *** Ndlondlo Snake Park ***
DECLARE @pid_Ndlondlo_Snake_Park INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Ndlondlo Snake Park', N'The park also gives courses on basic snake handling, first aid and how to handle snake encounters. All Guided tours that are offered, are facilitated by the most knowledgeable and professionally trained tour guides, we specialize in educating people about indigenous snakes.', N'Pay for 1 kids entry and get 1 free', 3, 1);
SET @pid_Ndlondlo_Snake_Park = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Ndlondlo_Snake_Park, N'Esenembe Road, Ballito', N'Ballito', N'KwaZulu Natal');

-- *** Nu Metro ***
DECLARE @pid_Nu_Metro INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Nu Metro', N'Get your popcorn and snacks and enjoy the latest selection of movies at NuMetro cinema', N'Buy 1 ticket and get 1 free ticket', 3, 1);
SET @pid_Nu_Metro = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'Cnr Jan Smuts Ave and, 6th Rd, Hyde Park, Johannesburg', N'Hyde Park', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'Loch Logan Waterfront, 105 Henry St & 1st Avenue, Westdene, Bloemfontein', N'Loch Logan', N'Free State');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'92 Atterbury Rd, Garston AH, Pretoria', N'Menlyn Park', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'77, 8 Jack Martens Dr, Westville, Durban,', N'The Pavilion', N'KwaZulu Natal');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'479, Century Blvd, Century City, Cape Town', N'Canal Walk', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'13 Mountain Mill Dr, Hospital Hill, Worcester', N'Mountain Mill', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'19, Summerstrand Boardwalk Casino, 2nd Ave, Summerstrand, Gqeberha', N'Boardwalk', N'Eastern Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'cnr Moss Kolnick Drive & Arbour Road, btw Ashgate Rd & Outer Ring Rd', N'Galleria', N'KwaZulu Natal');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'Emperors Palace, 64 Jones Road btw Griffiths Rd, Griffiths Rd & P Ln, Kempton Park', N'Emperors Palace', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'Garsfontein Rd &, De Villebois Mareuil Dr, Pretoriuspark, Pretoria', N'Woodlands', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'Ballito Dr, R627, Dolphin Coast,', N'Ballito Junction', N'KwaZulu Natal');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'Tecoma Road &, Allamanda Rd, Blackburn Estate, Blackburn', N'Cornubia', N'KwaZulu Natal');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'Westgate Shopping Centre, Westgate Rd, Horizon View, Roodepoort', N'Westgate', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'Tsamaya Ave &, J Maleleku Dr, Mahube Valley, Pretoria', N'Mams Mall', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'Giyani Main Rd, Giyani-BA, Giyani,', N'Masingita Mall', N'Limpopo');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'Kirkby Rd, Bedford Gardens, Johannesburg', N'Bedford', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Nu_Metro, N'Clearwater Mall, Hendrik Potgieter Rd & Christiaan De Wet Rd, Roodepoort', N'Clearwater', N'Gauteng');

-- *** Rush ***
DECLARE @pid_Rush INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Rush', N'Rush Extreme SA - Extreme Sports Park experience blending safety and fun. Exercise, entertain and jump with confidence in cutting-edge surroundings', N'Pay for all access ticket and get 1 free', 3, 1);
SET @pid_Rush = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Rush, N'Cnr van Riebeeck and, Modderfontein Rd, Greenstone Hill, Johannesburg, 1616', N'Johannesburg', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Rush, N'25 Stegman Rd, Claremont, Cape Town', N'Cape Town', N'Western Cape');

-- *** S.W.A.T Laser Tag ***
DECLARE @pid_S_W_A_T_Laser_Tag INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'S.W.A.T Laser Tag', N'S.W.A.T Laser Tag Offers a Variety of Thrilling Combat Games that the Whole Family can Enjoy.', N'Members get R500 discount per function of 10 or more players booked.', 3, 1);
SET @pid_S_W_A_T_Laser_Tag = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_S_W_A_T_Laser_Tag, N'127b Wroxham Rd, Paulshof, Fourways, Sandton', N'Fourways', N'Gauteng');

-- *** Saddle Creek Adventures ***
DECLARE @pid_Saddle_Creek_Adventures INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Saddle Creek Adventures', N'Saddle Creek Adventures is nestled in the Hekpoort Valley at the foot of the magnificent Magaliesberg Mountains. A mere 45 minutes drive from both Johannesburg and Pretoria, this picturesque adventure ranch venue is suitable for a fun filled family day out or as the perfect place to build team spirit or throw an adventurous function out in the wilderness.', N'Pay for 1 Laser Clay Pigeon Shooting 40 shots at 20 clays and get 1 free.', 3, 1);
SET @pid_Saddle_Creek_Adventures = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Saddle_Creek_Adventures, N'Farm HH24 Hartebeesfontein Road, Hekpoort', N'Hekpoort', N'Gauteng');

-- *** Splash Jump Zone ***
DECLARE @pid_Splash_Jump_Zone INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Splash Jump Zone', N'A Family orientated waterpark where friends and family can come and have fun. We have different thrill amazing swimming pools and adventurous waterslides.', N'Pay for 1 entry ticket and get 1 entry free', 3, 1);
SET @pid_Splash_Jump_Zone = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Splash_Jump_Zone, N'Plot 22 First Ave, Dalmada AH', N'Dalmada', N'Limpopo');

-- *** The Social Pallet ***
DECLARE @pid_The_Social_Pallet INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'The Social Pallet', N'The Social Pallet is about making art fun. Its where anyone can come and discover their artistic side. All materials are provided and you leave with a masterpiece on a pallet board. Isnt it time you did something for yourself.', N'Buy 1 art lesson at R250 a session and get 1 free', 3, 1);
SET @pid_The_Social_Pallet = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_The_Social_Pallet, N'1 Chester Terrace, Westville', N'Westville', N'KwaZulu Natal');

-- *** Total Ninja ***
DECLARE @pid_Total_Ninja INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Total Ninja', N'Our new Total Ninja Park is a supervised activity and fitness venue inspired by the need for individuals of all ages and abilities to achieve their own greatness. We are the largest inflatable and obstacle course in Africa.', N'Buy 1 mini ninja for 1 hour and get 1 free', 3, 1);
SET @pid_Total_Ninja = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Total_Ninja, N'Corner Modderfontein & Hereford Rd, Stoneridge Centre, Edenvale, Johannesburg', N'Johannesburg', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Total_Ninja, N'Entrance 6, Shop 267, Northgate Mall, Northumberland Ave, Northgate, Johannesburg', N'Johannesburg', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Total_Ninja, N'Entrance 2, Shop LG41, Kolonnade Shopping Centre, Sefako Makgatho Dr, Montana Park, Pretoria', N'Pretoria', N'Gauteng');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Total_Ninja, N'Gateway Theatre Of Shopping, 1 Palm Boulevard, Umhlanga Ridge', N'Umhlanga', N'KwaZulu Natal');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Total_Ninja, N'Shop 201, Westown Square, 600 Kassier Road, Shongweni, Durban', N'Durban', N'KwaZulu Natal');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Total_Ninja, N'Black River Park, South Park Entrance, 2 Fir St, Observatory, Cape Town', N'Cape Town', N'Western Cape');

-- *** Valley Crag ***
DECLARE @pid_Valley_Crag INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Valley Crag', N'', N'Pay for 1 day pass and get 1 free', 3, 1);
SET @pid_Valley_Crag = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Valley_Crag, N'16 Lower Valley Rd, South End, Gqeberha', N'Gqeberha', N'Eastern Cape');

-- *** Wild X Adventure ***
DECLARE @pid_Wild_X_Adventure INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Wild X Adventure', N'Wild X offers a wide variety of adventures for the whole family in and around various towns in the Garden Route and Cape Town South Africa.', N'Buy 1 paintball session and get 1 free', 3, 1);
SET @pid_Wild_X_Adventure = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Wild_X_Adventure, N'Boven Lange Valley Wilderness', N'Wilderness', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Wild_X_Adventure, N'Heatherlands George', N'George', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Wild_X_Adventure, N'Oysters Edge Restaurant, 7 Flamingo Avenue, Segdefield', N'Segdefield', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Wild_X_Adventure, N'43 Holt Hill, Bitou Rural, Plettenberg Bay', N'Plettenberg Bay', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Wild_X_Adventure, N'Greater Plettenberg Bay', N'Plettenberg Bay', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Wild_X_Adventure, N'Perdeskoendraai Farm R62 Oudtshoorn', N'Oudtshoorn', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Wild_X_Adventure, N'Freedom Village, R301 Wemmershoek Rd, Freedom Village, Paarl', N'Paarl', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Wild_X_Adventure, N'0 Dassenberg Dr, Atlantis, Cape Town', N'Atlantis Dunes', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Wild_X_Adventure, N'R72 Highway Cape Farms Melkbosstrand Cape Town', N'Cape Farms', N'Western Cape');
INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Wild_X_Adventure, N'Du Toitskloof Pass, N1, Paarl', N'Paarl', N'Western Cape');

-- *** Cape Town Tandem Paragliding ***
DECLARE @pid_Cape_Town_Tandem_Paragliding INT;
INSERT INTO book_partner (partner_name, partner_write_up, partner_offer, book_category_id, isActive)
VALUES (N'Cape Town Tandem Paragliding', N'We provide instructional training paragliding flights from Signal Hill and Lion''s Head. The paragliding launch site we use depends on the wind direction at the time. Sometimes we start flying from Signal Hill and then move across to Lion''s Head as the wind changes throughout the day.', N'Buy 1 get 1 free up to 100', 3, 1);
SET @pid_Cape_Town_Tandem_Paragliding = SCOPE_IDENTITY();

INSERT INTO book_branch (partner_id, address, branch_name, province)
VALUES (@pid_Cape_Town_Tandem_Paragliding, N'2 Signal Hill Rd, Signal Hill, Cape Town', N'Cape Town', N'Western Cape');

COMMIT;